name: deploy-hosted-and-wallet

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

concurrency:
  group: separate-wallet-host-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-wallet-host:
    environment: web3authn
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies (workspace)
        run: pnpm install --no-frozen-lockfile

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: Install wasm-pack
        run: |
          curl -sSf https://rustwasm.github.io/wasm-pack/installer/init.sh | sh

      - name: Build SDK (@tatchi-xyz/sdk, production)
        run: pnpm build:sdk-prod

      - name: Build wallet host example (if present)
        if: ${{ hashFiles('examples/vite/package.json') != '' }}
        env:
          VITE_WALLET_ORIGIN: ${{ vars.VITE_WALLET_ORIGIN }}
          VITE_WALLET_SERVICE_PATH: ${{ vars.VITE_WALLET_SERVICE_PATH }}
          VITE_SDK_BASE_PATH: ${{ vars.VITE_SDK_BASE_PATH }}
          VITE_RP_ID_BASE: ${{ vars.VITE_RP_ID_BASE }}
          VITE_RELAYER_URL: ${{ vars.VITE_RELAYER_URL }}
          VITE_RELAYER_ACCOUNT_ID: ${{ vars.VITE_RELAYER_ACCOUNT_ID }}
          VITE_NEAR_NETWORK: ${{ vars.VITE_NEAR_NETWORK }}
          VITE_NEAR_RPC_URL: ${{ vars.VITE_NEAR_RPC_URL }}
          VITE_NEAR_EXPLORER: ${{ vars.VITE_NEAR_EXPLORER }}
        run: pnpm -C examples/vite build

      - name: Copy SDK assets into Pages output (example)
        if: ${{ hashFiles('examples/vite/package.json') != '' }}
        run: |
          mkdir -p examples/vite/dist/sdk examples/vite/dist/sdk/workers
          rsync -av --delete sdk/dist/esm/sdk/ examples/vite/dist/sdk/
          # Include web workers + colocated WASM binaries expected at /sdk/workers
          if [ -d sdk/dist/workers ]; then
            rsync -av --delete sdk/dist/workers/ examples/vite/dist/sdk/workers/
          fi

      - name: Fail if example missing
        if: ${{ hashFiles('examples/vite/package.json') == '' }}
        run: |
          echo "::error::Missing wallet host example at examples/vite" >&2
          echo "Create it (docs cover how) or add a CI fallback again." >&2
          exit 1

      - name: Deploy example to Cloudflare Pages (wallet host)
        if: ${{ hashFiles('examples/vite/package.json') != '' }}
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CF_PAGES_PROJECT_WALLET }}
          directory: examples/vite/dist

      # No fallback: example is required for this workflow

  deploy-hosted-app:
    environment: hosted
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: Install wasm-pack
        run: |
          curl -sSf https://rustwasm.github.io/wasm-pack/installer/init.sh | sh

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies (workspace)
        run: pnpm install --no-frozen-lockfile

      - name: Build SDK (@tatchi-xyz/sdk, production)
        run: pnpm build:sdk-prod

      - name: Build hosted app (examples/vite)
        env:
          VITE_WALLET_ORIGIN: ${{ vars.VITE_WALLET_ORIGIN }}
          VITE_WALLET_SERVICE_PATH: ${{ vars.VITE_WALLET_SERVICE_PATH }}
          VITE_SDK_BASE_PATH: ${{ vars.VITE_SDK_BASE_PATH }}
          VITE_RP_ID_BASE: ${{ vars.VITE_RP_ID_BASE }}
          VITE_RELAYER_URL: ${{ vars.VITE_RELAYER_URL }}
          VITE_RELAYER_ACCOUNT_ID: ${{ vars.VITE_RELAYER_ACCOUNT_ID }}
          VITE_NEAR_NETWORK: ${{ vars.VITE_NEAR_NETWORK }}
          VITE_NEAR_RPC_URL: ${{ vars.VITE_NEAR_RPC_URL }}
          VITE_NEAR_EXPLORER: ${{ vars.VITE_NEAR_EXPLORER }}
        run: pnpm -C examples/vite build

      - name: Deploy hosted app to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CF_PAGES_PROJECT_HOSTED }}
          directory: examples/vite/dist
